apiVersion: v1
kind: Pod
metadata:
  name: pod-ports
  #namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports: # 设置容器暴露的端口列表
        - name: nginx-port
          containerPort: 80
          protocol: TCP